# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
