# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shoes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_shoe',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='分类'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoes',
            name='views',
            field=models.IntegerField(default=1, verbose_name='浏览量'),
        ),
    ]
