# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand', models.IntegerField(verbose_name='评分')),
                ('user', models.CharField(max_length=30, verbose_name='评分用户')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.AddField(
            model_name='brank',
            name='bcontent',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='品牌详情'),
            preserve_default=False,
        ),
    ]
