# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180623_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_pic',
            name='pic',
            field=models.ImageField(blank=True, upload_to='static/images/', verbose_name='图片'),
        ),
    ]
