# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180624_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='is_recommend',
            field=models.BooleanField(default=True, verbose_name='人民币推荐Banner图'),
        ),
    ]
